version: 2.1

jobs:
  test:
    parameters:
      suite:
        type: string
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-v1-{{ checksum "pom.xml" }}
            - maven-v1-
      - run:
          name: Run << parameters.suite >>
          command: mvn -B clean test -Dtestng.suite=<< parameters.suite >>
      - save_cache:
          key: maven-v1-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
      - store_test_results:
          path: target/surefire-reports/junitreports
      - store_artifacts:
          path: target/surefire-reports

workflows:
  test:
    jobs:
      - test:
          name: smoke
          suite: testngSmoke.xml
      - test:
          name: regression
          suite: testngRegression.xml